apiVersion: app/v1
kind: Deployment
metadata:
  name: python-app
  labels:
    name: python-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: python-app
  template:
    metadata:
      name: python-app
      labels:
        name: python-app
    spec:
      containers:
        - name: python-app
          image: jtorresheredia/python-app:v1
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: 128Mi
            limits:
              memory: 256Mi
          env:
            - name: PORT
              value: "8080"
            - name: DEBUG_MODE
              value: "1"
